### ISSUE TITLE
Card API v2

### ISSUE THREAD

**Issue by HarrisonTotty** [HarrisonTotty/fab#9]
Was thinking of some ways to better implement `Card` objects. I'm debating the idea of having `Catalog` objects which essentially contain all data that the `CardList` and `CardSetCollection` objects contain, but with dynamic indexing for better searching. We could then redefine a particular `Card` be something like:

```yaml
# Card Object Example
# -------------------

apiVersion: v1
kind: Card
metadata:
  uid: U-WTR043-M-S
  edition: U
  flavor_text: null
  foiling: S
  identifier: WTR043
  name: Crippling Crush
  image_url: >-
    https://...
  legality:
    B: true
    C: true
    CC: true
    D: true
    UPF: true
  rarity: M
  release_date: 'YY/MM/DD'
  set: WTR
  tags:
    - example
spec:
  cost: 7
  body: >-
    **Bravo Specialization** _(You may...
  defense: 3
  grants: null
  health: null
  intelligence: null
  keywords:
    - 'Bravo Specialization'
    - 'Crush'
  pitch: 1
  power: 11
  type_text: >-
    Guardian Action - Attack
  types: ['Guardian', 'Action', 'Attack']
```
Perhaps the above is really a `CardVariant` as opposed to a `Card` (much like an `InventoryItem`).
